import { DatasetSize } from '../enums/dataset-size.enum';
import { JobTitle } from '../enums/job-title.enum';
import { Employee } from '../interfaces/employee.interface';
import { v4 as uuid} from 'uuid';

const data: Employee[] = [
  {name: 'Hasad Harmon', jobTitle: JobTitle.HrExpert, age: 71},
  {name: 'Zachary Chang', jobTitle: JobTitle.BackendDev, age: 16},
  {name: 'Gray Bush', jobTitle: JobTitle.BackendDev, age: 76},
  {name: 'Sylvester Blanchard', jobTitle: JobTitle.FrontendDev, age: 33},
  {name: 'Hunter Kent', jobTitle: JobTitle.HrExpert, age: 33},
  {name: 'Alvin Mercado', jobTitle: JobTitle.HrExpert, age: 94},
  {name: 'Dean Thompson', jobTitle: JobTitle.HrExpert, age: 86},
  {name: 'Stone Hodge', jobTitle: JobTitle.BackendDev, age: 89},
  {name: 'Wesley Ramos', jobTitle: JobTitle.BackendDev, age: 16},
  {name: 'Brent Mckinney', jobTitle: JobTitle.HrExpert, age: 52},
  {name: 'Trevor Rodriguez', jobTitle: JobTitle.HrExpert, age: 43},
  {name: 'Coby Fleming', jobTitle: JobTitle.BackendDev, age: 48},
  {name: 'Victor Faulkner', jobTitle: JobTitle.FrontendDev, age: 97},
  {name: 'Wang Banks', jobTitle: JobTitle.FrontendDev, age: 26},
  {name: 'Jelani Kirk', jobTitle: JobTitle.HrExpert, age: 64},
  {name: 'Chadwick Guerrero', jobTitle: JobTitle.FrontendDev, age: 57},
  {name: 'Carlos Obrien', jobTitle: JobTitle.BackendDev, age: 77},
  {name: 'Yardley Beard', jobTitle: JobTitle.FrontendDev, age: 72},
  {name: 'Oliver Fox', jobTitle: JobTitle.FrontendDev, age: 48},
  {name: 'Vladimir Lopez', jobTitle: JobTitle.FrontendDev, age: 54},
  {name: 'Cameron Mccall', jobTitle: JobTitle.BackendDev, age: 36},
  {name: 'Chadwick Pate', jobTitle: JobTitle.HrExpert, age: 78},
  {name: 'Malachi Jones', jobTitle: JobTitle.FrontendDev, age: 45},
  {name: 'Driscoll Tyson', jobTitle: JobTitle.BackendDev, age: 54},
  {name: 'Perry Chaney', jobTitle: JobTitle.FrontendDev, age: 36},
  {name: 'Kenyon Barnett', jobTitle: JobTitle.BackendDev, age: 40},
  {name: 'Shad Alvarez', jobTitle: JobTitle.FrontendDev, age: 49},
  {name: 'Hasad Mooney', jobTitle: JobTitle.HrExpert, age: 48},
  {name: 'Conan Barnett', jobTitle: JobTitle.FrontendDev, age: 80},
  {name: 'Barrett Simmons', jobTitle: JobTitle.BackendDev, age: 87},
  {name: 'Jarrod Johnson', jobTitle: JobTitle.BackendDev, age: 59},
  {name: 'Francis Obrien', jobTitle: JobTitle.FrontendDev, age: 80},
  {name: 'Kasimir Gardner', jobTitle: JobTitle.BackendDev, age: 90},
  {name: 'Harrison Holden', jobTitle: JobTitle.FrontendDev, age: 12},
  {name: 'Clark Armstrong', jobTitle: JobTitle.BackendDev, age: 58},
  {name: 'Kato Edwards', jobTitle: JobTitle.BackendDev, age: 91},
  {name: 'Allistair Espinoza', jobTitle: JobTitle.FrontendDev, age: 82},
  {name: 'Brian Irwin', jobTitle: JobTitle.BackendDev, age: 16},
  {name: 'Zachary Guerra', jobTitle: JobTitle.BackendDev, age: 69},
  {name: 'Oscar Clarke', jobTitle: JobTitle.HrExpert, age: 15},
  {name: 'Harper Wong', jobTitle: JobTitle.FrontendDev, age: 70},
  {name: 'Simon Stevenson', jobTitle: JobTitle.FrontendDev, age: 18},
  {name: 'Nash Cash', jobTitle: JobTitle.FrontendDev, age: 72},
  {name: 'Cruz Rose', jobTitle: JobTitle.HrExpert, age: 19},
  {name: 'Tobias Alston', jobTitle: JobTitle.HrExpert, age: 85},
  {name: 'Armando Holden', jobTitle: JobTitle.FrontendDev, age: 47},
  {name: 'Damon Richards', jobTitle: JobTitle.FrontendDev, age: 26},
  {name: 'Samson Keller', jobTitle: JobTitle.HrExpert, age: 16},
  {name: 'Hyatt Pace', jobTitle: JobTitle.HrExpert, age: 94},
  {name: 'Aristotle Sosa', jobTitle: JobTitle.HrExpert, age: 38},
  {name: 'Gavin Cannon', jobTitle: JobTitle.FrontendDev, age: 99},
  {name: 'Paul Byers', jobTitle: JobTitle.BackendDev, age: 67},
  {name: 'Chaim Sweet', jobTitle: JobTitle.FrontendDev, age: 53},
  {name: 'Chester Crosby', jobTitle: JobTitle.BackendDev, age: 31},
  {name: 'Gil Macias', jobTitle: JobTitle.HrExpert, age: 10},
  {name: 'Emery Hickman', jobTitle: JobTitle.HrExpert, age: 11},
  {name: 'Alan Wells', jobTitle: JobTitle.HrExpert, age: 77},
  {name: 'Myles Garner', jobTitle: JobTitle.FrontendDev, age: 82},
  {name: 'Herrod Estrada', jobTitle: JobTitle.HrExpert, age: 73},
  {name: 'Fulton Ayala', jobTitle: JobTitle.BackendDev, age: 13},
  {name: 'Ishmael Holman', jobTitle: JobTitle.HrExpert, age: 45},
  {name: 'Joshua Lawrence', jobTitle: JobTitle.FrontendDev, age: 82},
  {name: 'Rigel Young', jobTitle: JobTitle.FrontendDev, age: 60},
  {name: 'Cyrus Klein', jobTitle: JobTitle.HrExpert, age: 97},
  {name: 'Cedric Ryan', jobTitle: JobTitle.FrontendDev, age: 65},
  {name: 'Lucius Mcdonald', jobTitle: JobTitle.BackendDev, age: 43},
  {name: 'Norman Dillard', jobTitle: JobTitle.BackendDev, age: 92},
  {name: 'Clarke Browning', jobTitle: JobTitle.BackendDev, age: 83},
  {name: 'Reese Santiago', jobTitle: JobTitle.HrExpert, age: 20},
  {name: 'Burton William', jobTitle: JobTitle.FrontendDev, age: 94},
  {name: 'Solomon Doyle', jobTitle: JobTitle.FrontendDev, age: 85},
  {name: 'Dean Davis', jobTitle: JobTitle.HrExpert, age: 21},
  {name: 'Richard Washington', jobTitle: JobTitle.FrontendDev, age: 93},
  {name: 'Callum Mcguire', jobTitle: JobTitle.HrExpert, age: 33},
  {name: 'Fulton Patterson', jobTitle: JobTitle.HrExpert, age: 96},
  {name: 'Jonah Vasquez', jobTitle: JobTitle.HrExpert, age: 63},
  {name: 'Murphy Weaver', jobTitle: JobTitle.HrExpert, age: 56},
  {name: 'Ira Joyce', jobTitle: JobTitle.BackendDev, age: 83},
  {name: 'Abel Robbins', jobTitle: JobTitle.FrontendDev, age: 90},
  {name: 'Harper Lang', jobTitle: JobTitle.BackendDev, age: 62},
  {name: 'Merrill Hayden', jobTitle: JobTitle.BackendDev, age: 34},
  {name: 'Baker Hines', jobTitle: JobTitle.FrontendDev, age: 53},
  {name: 'Dean Mejia', jobTitle: JobTitle.BackendDev, age: 24},
  {name: 'Griffin Davidson', jobTitle: JobTitle.HrExpert, age: 90},
  {name: 'Emerson Clayton', jobTitle: JobTitle.FrontendDev, age: 89},
  {name: 'Brett Lowery', jobTitle: JobTitle.BackendDev, age: 51},
  {name: 'Darius Hodge', jobTitle: JobTitle.BackendDev, age: 40},
  {name: 'Galvin Spears', jobTitle: JobTitle.BackendDev, age: 39},
  {name: 'Patrick Booth', jobTitle: JobTitle.HrExpert, age: 76},
  {name: 'Kyle Mckay', jobTitle: JobTitle.HrExpert, age: 84},
  {name: 'Graiden Murphy', jobTitle: JobTitle.BackendDev, age: 11},
  {name: 'Isaac Wise', jobTitle: JobTitle.BackendDev, age: 88},
  {name: 'Alec Hamilton', jobTitle: JobTitle.FrontendDev, age: 17},
  {name: 'Malcolm Leblanc', jobTitle: JobTitle.FrontendDev, age: 76},
  {name: 'Mannix Bennett', jobTitle: JobTitle.FrontendDev, age: 91},
  {name: 'Garrett Watts', jobTitle: JobTitle.BackendDev, age: 85},
  {name: 'Channing Dixon', jobTitle: JobTitle.HrExpert, age: 72},
  {name: 'Bradley Valdez', jobTitle: JobTitle.HrExpert, age: 21},
  {name: 'Eric Allen', jobTitle: JobTitle.FrontendDev, age: 59},
  {name: 'Jackson Ratliff', jobTitle: JobTitle.BackendDev, age: 63},
];

export const tenItems: Employee[] = data.slice(0, 10).map(el => ({...el, key: uuid()}));;

export const oneHundredItems: Employee[] = data.slice().map(el => ({...el, key: uuid()}));

export const oneThousandItems: Employee[] = [
  ...data,
  ...data,
  ...data,
  ...data,
  ...data,
  ...data,
  ...data,
  ...data,
  ...data,
  ...data,
].map(el => ({...el, key: uuid()}));;

export const tenThousandsItems: Employee[] = [
  ...oneThousandItems,
  ...oneThousandItems,
  ...oneThousandItems,
  ...oneThousandItems,
  ...oneThousandItems,
  ...oneThousandItems,
  ...oneThousandItems,
  ...oneThousandItems,
  ...oneThousandItems,
  ...oneThousandItems,
].map(el => ({...el, key: uuid()}));;

export const twentyThousandsItems: Employee[] = [
  ...tenThousandsItems,
  ...tenThousandsItems,
].map(el => ({...el, key: uuid()}));;

export const dataMap  = {
  [DatasetSize.None]: [],
  [DatasetSize.TenItems]: tenItems,
  [DatasetSize.OneHundredItems]: oneHundredItems,
  [DatasetSize.OneThousandItems]: oneThousandItems,
  [DatasetSize.TenThousandsItems]: tenThousandsItems,
  [DatasetSize.TwentyThousandsItems]: twentyThousandsItems,
  
}